{% set name = "celerite" %}
{% set version = "0.4.3" %}
{% set sha256 = "aa8b487f57a7cc9793c4652b19b2df090beaa849730b50805f030694e94d0f6d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - pybind11
    - numpy
  run:
    - python
    - setuptools  # [win]
    - vs2015_runtime  # [win]

test:
  imports:
    - celerite

about:
  home: http://github.com/dfm/celerite
  license: MIT
  license_file: LICENSE
  summary: Scalable 1D Gaussian Processes in C++ and Python
  doc_url: http://celerite.readthedocs.io/
  dev_url: https://github.com/dfm/celerite

extra:
  recipe-maintainers:
    - dfm
