{% set name = "celerite" %}
{% set version = "0.4.2" %}
{% set sha256 = "65afd3f3e6f11421d1d8868da5fdca7318a892aea02b994b618e0ac8f3e4a92d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - pybind11
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - setuptools  # [win]
    - vs2015_runtime  # [win]

test:
  imports:
    - celerite

about:
  home: http://github.com/dfm/celerite
  license: MIT
  license_file: LICENSE
  summary: Scalable 1D Gaussian Processes in C++ and Python
  doc_url: http://celerite.readthedocs.io/
  dev_url: https://github.com/dfm/celerite

extra:
  recipe-maintainers:
    - dfm
